# NumPy

NumPy is an open seurce Python library that's used in almost every field of science and engineering , 
It's the universal standdard for working with numerical data in Python , And it's at core of the scientific Python and PyData ecosystems.
NumPy can be ussed to Performs a Wide variety of mathematical Operation on arrys. It adds powerful data structures to Python that guarantee effcient calculations with arrys and matrics and it supplies an enormus library of high-level mathematical function that operate on these arrays and matrics .
It also has function for working in domain of linear  algebra ,fourier transform , matrics .NumPy was created in 2005 by Travis Oliphant .
It is and open source and u can used it freely
The numePy library contains a multidimensional array and matrix data structures.

# Why use NumPy ?

In python we have lists that purpose of array , but they are slow to process,
NumPy aims to provide an array object that is up to 50x faster than traditinal Python lists. 
The array object in numpy  is called ndarray , it provides a lot of supporting function that make working with ndarray very easy.
Array are very frequently used in data science , where speed and resources are important.
## Key Features of NumPy

### 1.Efficient Array Operations:
NumPy arrays are stored in contiguous memory locations, making them faster and more efficient than Python lists. This is due to the locality of reference, which allows for quicker access and manipulation of data.
### 2.Multidimensional Arrays:
NumPy supports arrays with multiple dimensions, allowing for complex data structures. The number of dimensions is called the rank, and the shape of the array is a tuple of integers representing the size along each dimension.
### 3.Mathematical Functions: 
NumPy provides a wide range of mathematical functions for operations such as addition, subtraction, multiplication, division, and more. These operations can be performed element-wise on arrays.
### 4.Broadcasting: 
NumPy supports broadcasting, which allows for operations between arrays of different shapes. This feature is useful for performing operations between a vector and a scalar or between arrays of different sizes.
### 5.Indexing and Slicing: 
NumPy arrays can be indexed and sliced in various ways, similar to Python lists. This allows for easy access and manipulation of specific elements or subarrays.

# Why is NumPy Faster than Lists ?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate then very efficiently.
This behavior is called locality of reference in computer science.
### NumPy arrays are faster than Python lists due to several key reasons:
### 1.Homogeneous Data Types:
NumPy arrays store elements of the same data type, which allows for optimized memory usage and faster operations. Python lists, on the other hand, can store mixed data types, which adds overhead.

### 2.Contiguous Memory Allocation:
NumPy arrays are stored in contiguous memory blocks, enabling efficient access and manipulation. Python lists are stored as pointers to objects, which increases memory fragmentation and slows down operations.

### 3.Vectorization:
NumPy supports vectorized operations, meaning you can perform element-wise computations without explicit loops. This leverages low-level C implementations, making operations significantly faster compared to Python's interpreted loops.

### 4.Efficient Memory Management:
NumPy uses less memory compared to Python lists because it avoids the overhead of storing type information for each element. This compact storage improves performance, especially for large datasets.

### 5.Built-in Optimizations:
NumPy is implemented in C and Fortran, which are highly optimized for numerical computations. Python lists rely on Python's general-purpose implementation, which is slower for numerical tasks.

In [4]:
import numpy as np

In [2]:
python_list=[1,2,3,4,5,6]
print(python_list)

[1, 2, 3, 4, 5, 6]


In [2]:
arr= np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
arr=np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


# Dimensions in array

# 0 D Array

In [5]:
arr=np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


# 1 D Array

In [6]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


# 2 D Array


In [7]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


# 3 D Array

In [8]:
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>
3


In [9]:
a=np.array(20)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3,4],[5,6,7,8]])
d=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Array vs List

In [7]:
py_list=[1,2,3,4]
print("Python list multiplication :",py_list*2)
py_array= np.array([1,2,3,4])
print("Python array multiplication :",py_array*2)


Python list multiplication : [1, 2, 3, 4, 1, 2, 3, 4]
Python array multiplication : [2 4 6 8]


## Creating Array from scratch

In [10]:
zeros=np.zeros((3,4))
print("zeros arrays:\n ",zeros)

zeros arrays:
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ones=np.ones((2,3))
print("ones arrays:\n ",ones)

ones arrays:
  [[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
full=np.full((2,2),7)
print("full arrays:\n ",full)

full arrays:
  [[7 7]
 [7 7]]


In [13]:
randoms=np.random.random((2,3))
print("randoms arrays:\n ",randoms)

randoms arrays:
  [[0.782046   0.21379185 0.11464806]
 [0.93038851 0.0451661  0.56100852]]


In [14]:
sequence= np.arange(0,10,2)
print("sequence arrays:\n ",sequence)

sequence arrays:
  [0 2 4 6 8]


## Vector,Matrix and Tensor

In [15]:
vector=np.array([1,2,3,4])
print("vector:\n ",vector)

vector:
  [1 2 3 4]


In [16]:
matrix=np.array([[1,2,3,4],[5,6,7,8]])
print("matrix:\n ",matrix)
            

matrix:
  [[1 2 3 4]
 [5 6 7 8]]


In [17]:
tensor=np.array([[[1,2],[3,4]],
                [[5,6],[7,8]]])
print("tensor:\n ",tensor)

tensor:
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties

In [18]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(" Shape :\n",arr.shape)
print(" Dimension :\n",arr.ndim)
print(" Size :\n",arr.size)
print(" DataType :\n",arr.dtype)




 Shape :
 (2, 3)
 Dimension :
 2
 Size :
 6
 DataType :
 int64


## Array Reshaping

In [16]:
#1D array
arr=np.arange(12)
print("1..Original array :\n",arr)

# in to 2D array
reshaped=arr.reshape((3,4))
print("\n 2..Reshaped array :\n",reshaped)

flattened = reshaped.flatten()
print("\n 3..Flattened array :\n",flattened)

# ravel (returns view,instead of copy)
raveled = reshaped.ravel()
print("\n 4..Raveled array :\n",raveled)

# transpose
transpose=reshaped.T
print("\n 5..Transposed array :\n",transpose)

1..Original array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 2..Reshaped array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 3..Flattened array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 4..Raveled array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 5..Transposed array :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# NumPy Array operations

In [5]:
arr=np.array([1,2,3,4,5,6,9,11,22,13])
print("Basics Slicing",arr[2:7])
print("With Step",arr[1:5:2])
print("Negative indrxing",arr[-3])

Basics Slicing [3 4 5 6 9]
With Step [2 4]
Negative indrxing 11


# 2D

In [8]:
arr_2d=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
print("Specific Element ", arr_2d[1,2])
print("Entire row ",arr_2d[1])
print("Entire colomn ",arr_2d[:,1])


Specific Element  7
Entire row  [5 6 7 8]
Entire colomn  [ 2  6 10]


# Sorting

In [16]:
unsorted=np.array([1,2,32,3,4,3,4,5,7,89,6,5,4,56,4,3,5,67,8,9])
print("Sorted Array ",np.sort(unsorted))
arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d array by colomn\n",np.sort(arr_2d_unsorted,axis=0))

Sorted Array  [ 1  2  3  3  3  4  4  4  4  5  5  5  6  7  8  9 32 56 67 89]
Sorted 2d array by colomn
 [[1 1]
 [2 2]
 [3 3]]


# Filter

In [17]:
numbers=np.array([1,2,3,4,5,6,7,8,9])
even_numbers=numbers[numbers%2==0]
print("Even numbers ",even_numbers)


Even numbers  [2 4 6 8]


# Filter With mask

In [19]:
mask=numbers>5
print("Numbers greater than 5",numbers[mask])

Numbers greater than 5 [6 7 8 9]


# Real warld decision rule ,conditional filtring

In [4]:
prices= np.array([500,389,675,908,900,700,489,89,348,100])
discount = prices -200
discount[discount<100]=100
print(discount)

[300 189 475 708 700 500 289 100 148 100]


In [5]:
balances=np.array([500,2000,1000,5000,6000,70])
balances[balances<1000]-=50
balances[balances>=1000]-=20
print(balances)

[ 450 1980  980 4980 5980   20]


In [15]:
salary = np.array([300000, 56000, 78000, 23000, 65000, 10000])
salary = salary.astype(float)
salary[salary < 30000] *= 1.10
salary[(salary >= 30000) & (salary <= 60000)] *= 1.05
salary[salary > 60000] *= 1.02

print(salary)



[306000.  58800.  79560.  25300.  66300.  11000.]


In [17]:
# Replace all  negative values with zero (0)
arr=np.array([4,5,6,7,-2,4,-56,-2,54,-66])
arr[arr<0]=0
arr

array([ 4,  5,  6,  7,  0,  4,  0,  0, 54,  0])

In [18]:
# Extract all values between two numbers
arr=np.array([10,23,4,5,66,5,43,23,67,45,11,22,])
arr[(arr>10)&(arr<=30)]

array([23, 23, 11, 22])

In [19]:
# Count unique value and their two numbers
arr=np.array([10,3,44,56,34,80,23,4,4,4,4,4,4,10,10,10,10,10,10,44,44,44,44])
unique,count = np.unique(arr,return_counts=True)
unique,count

(array([ 3,  4, 10, 23, 34, 44, 56, 80]), array([1, 6, 7, 1, 1, 5, 1, 1]))

In [20]:
# stack two arrays vertically and horizontlly
a= np.array([1,2,3])
b=np.array([4,5,6])
v=np.vstack([a,b])
h=np.hstack([a,b])
v,h

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]))

In [23]:
# Convert a NumPy Array of Strings to Uppercase
arr= np.array(["Kishan","Neeraj","Manish","om"])
np.char.upper(arr)# captilize

array(['KISHAN', 'NEERAJ', 'MANISH', 'OM'], dtype='<U6')

# Assignment (NumPy)

In [2]:
# 1. Write a program to create a 1D and 2D NumPy array from a Python list and tuple. 
import numpy as np
py_list=[1,2,3,4]
py_tuple=(5,6,8,9)
arr1D_list=np.array(py_list)
arr1D_tuple=np.array(py_tuple)
mat=[[1,2,3],[4,5,6]]
arr2D=np.array(mat)
print(arr1D_list,arr1D_tuple,sep="\n")
print(arr2D)

[1 2 3 4]
[5 6 8 9]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 2. Write a program to display the shape, dimension,size and data type of a NumPy array.
arr=np.array([[1,2,3],
              [4,5,6]])
print(" Shape :\n",arr.shape)
print(" Dimension :\n",arr.ndim)
print(" Size :\n",arr.size)
print(" DataType :\n",arr.dtype)

In [3]:
# 3. Create an array, then make a copy and a view of it. Change one element and show how the original array is affected in each case.
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
flat_arr=arr.flatten()
flat_arr=arr.ravel()
flat_arr[0]=100
flat_arr[1]=200
print("Original\n",arr)
print()
print("copy: ",flat_arr)
print()
print("view :",flat_arr)

Original
 [[100 200   3]
 [  4   5   6]]

copy:  [100 200   3   4   5   6]

view : [100 200   3   4   5   6]


In [ ]:
# 4. Create a 3×3 NumPy array and add a 1D array [1, 2, 3] to it using broadcasting. Print the result.


In [5]:
# 5.  Create a 2D array and print its flattened version using both flatten() and ravel() methods. Check if changing one affects the original array.
arr=np.arange(12)
print("1..Original array :\n",arr)
# in to 2D array
reshaped=arr.reshape((3,4))
print("\n 2..Reshaped array :\n",reshaped)
flattened = reshaped.flatten()
print("\n 3..Flattened array :\n",flattened)
# ravel (returns view,instead of copy)
raveled = reshaped.ravel()
print("\n 4..Raveled array :\n",raveled)

1..Original array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 2..Reshaped array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 3..Flattened array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 4..Raveled array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
# 6. Create an array with duplicate elements and display the unique values and their counts.
arr=np.array([10,3,44,56,34,80,23,4,4,4,4,4,4,10,10,10,10,10,10,44,44,44,44])
unique,count = np.unique(arr,return_counts=True)
unique,count

(array([ 3,  4, 10, 23, 34, 44, 56, 80]), array([1, 6, 7, 1, 1, 5, 1, 1]))

In [ ]:
# 7. Create two 3×3 arrays and perform both element-wise (*) and matrix (@) multiplication.


In [11]:
# 8.  Create an array containing some np.nan values. Replace all NaN with the mean of the non-NaN elements.
arr=np.array([1,2,np.nan,3,np.nan,4])
mean=np.nanmean(arr)
arr_fill=np.where(np.isnan(arr),mean,arr)
print("Original\n",arr)
print()
print("mean ",mean)
print()
print("Filled:",arr_fill)

Original
 [ 1.  2. nan  3. nan  4.]

mean  2.5

Filled: [1.  2.  2.5 3.  2.5 4. ]


In [14]:
# 9. Create a structured array with fields — name (string), age (int), and marks (float). Display all student names whose marks > 80.
dtype=np.dtype([('name','U10'),('age','i4'),('marks','f4')])
students=np.array([('kishan',21,98.2),('Neeraj',22,85.5)],dtype=dtype)
high=students[students['marks']>80.0]
for i in high:
    print(i['name'],i['marks'])

kishan 98.2
Neeraj 85.5


In [ ]:
# 10. Write a program to compute the mean, median, standard deviation, and variance of a given NumPy array.
